### ISSUE TITLE
Possible layout to consider?

### ISSUE THREAD

**Issue by AngstyDuck** [OpenSUTD/SAC-student-rules#1]
Splitting the policy into club/non-club users allows us to specify differing privileges/responsibilities between both users. So perhaps we can consider this format below? (details can be mapped out subsequently, the ones I've wrote are just suggestions)

# Introduction
The *Student Activity Centre* (SAC) is a student-led space in the Fabrication Lab block. It is a space for student clubs and research groups to conduct their activities and more.
This is a living document, and policy suggestions are welcome: Just make sure you raise an issue!

# Core Philosophy
The SAC is a place that is there to **support student activities and provide them an enclosed space to work**. It is primarily _not_ a storage space (excepting the rooms, which are used by student clubs).

# For Independent Users
### General Etiquette
cleaning after yourself and clearing garbage bin whenever full as a means to protect the space from pests; food and drinks policy;  
### Storage of items
Storage only allowed in approved storage devices. Storage in open areas and unreported storage in storage devices will be cleared in ___ working days. 
### Booking of SAC
Explain how SAC may be booked for club activities. Detail out extent of restriction of access of users that are not part of club activities.
### Steps to follow when you:
- want to store items in storage devices 
- can't find your items
- report faulty equipment/item
- want to suggest policy changes (if they githubaphobia)
### FAQ
Answer misc questions

# For school clubs and societies
### General Etiquette
same content
### Storage of items
Storage only allowed in approved storage devices and rooms. Room policy (restrictions on what to store, etc.). Failure to adhere to room policy will result in ___.
### Booking of SAC space
Booking formats; Booking policy (can't book too long, clean up after use, etc.); Failure to adhere will result in ___.
### Steps to follow when you:
- can't find your items
- report faulty equipment/item
- apply for room space
- apply to book for events
### FAQ
Answer misc questions

**Comment by piroton** [comment]
I'll look into a re-write for this.
