### ISSUE TITLE
[ROOM] Grub Weekly Activities

### ISSUE THREAD

**Issue by 0nicholasloh** [OpenSUTD/SAC-student-rules#11]
**Requester**
Grub Club

**What is the purpose?**
Regular club activities 

**Who is the Point of Contact?**
Nicholas Loh (nicholas_loh(at)mymail(dot).sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
Thursday, 6th June 2019, 7pm - 7.15pm, 9.45pm - 10pm

**Is this recurring? If yes, how often?**
Yes, Weekly

**Comment by piroton** [comment]
I'll try to ensure that someone is there by 7!

**Comment by 0nicholasloh** [comment]
Hi can the room be opened today (20/6/19) at 6.15pm-6.30pm and at 9.15pm-9.30pm?

**Comment by 0nicholasloh** [comment]
Could the room be opened tomorrow (4/7/19) from 6.45 pm to 7pm and from 9pm - 9.15pm?

**Comment by piroton** [comment]
It should be made available! Sorry about the delay; had to check to make sure that people were available for it.

**Comment by 0nicholasloh** [comment]
Could the room be opened tomorrow (24 July) at 6pm, and locked at 10pm?

**Comment by lyqht** [comment]
@0nicholasloh , unfortunately, the earliest person that could make it to SAC due to work would reach around 6.30pm. Is that okay with you?

**Comment by 0nicholasloh** [comment]
6.30pm would be ok with us. Thanks a lot!

**Comment by 0nicholasloh** [comment]
Hi, could we get the room to be opened on 5/8/19 from 7.30 - 7.45 to retrieve equipment and on 7/8/19 from 7.15 -7.30 to return equipment.

**Comment by 0nicholasloh** [comment]
Hi, could we get the room to be opened on  26/8/19 from 4.45 to 5.00 to retrieve equipment and from 7.00 - 7.15 on the same date to return equipment.

**Comment by lyqht** [comment]
@0nicholasloh, are you sure you want it to be opened on August? haha
If you mean 26/9/19, yes it will be opened for you.

**Comment by 0nicholasloh** [comment]
Yup, sorry I meant 26/9/19, from 5:00 - 5:15

**Comment by 0nicholasloh** [comment]
Hi, could we get the room to be opened this Tuesday, 8 October 2019 from 7.00 pm to 7.15 pm and also on Thursday, 10 October 2019 6.15 pm to 6.30 pm and 8.00 pm to 8.15 pm?

**Comment by 0nicholasloh** [comment]
Hi, could we get the room to be opened this Thursday, 17 October 2019 from 6.45 pm to 7 pm and 9 pm to 9.15 pm?

**Comment by 0nicholasloh** [comment]
Hi, could I get the room to be opened at around 1.40pm on 18 Oct 2019?

**Comment by piroton** [comment]
> Hi, could I get the room to be opened at around 1.40pm on 18 Oct 2019?

I'll have it open - but this is uncharacteristic - what for, if it's not sensitive?

**Comment by 0nicholasloh** [comment]
Hi, could I get the room to be opened from 9 pm - 9.15 pm on 21 October 2019 to retrieve some items from the room and from 10.15 - 10.30 to return items?

**Comment by 0nicholasloh** [comment]
Hi, could I get the room to be opened from 4.45 pm - 5 pm on 24 October 2019 and from 7 pm to 7.15 pm?  We need access to the room during these times to retrieve items for our weekly session

**Comment by lyqht** [comment]
okay!

**Comment by 0nicholasloh** [comment]
Hi could we access the room on 25 October 2019 from 3.45 pm to 4.15 pm and on 26 October 2019 from 1 pm - 5 pm to retrieve our items for our participation in the STEM camp?

**Comment by Kazykiddo** [comment]
Hi Nic, this is a rather late notice, next time please let us know ahead of time, as some of us have exams until 4.30. We have designated someone to open the door for you on the 25th. Can you be more specific with the timing on the 26th of October?

**Comment by 0nicholasloh** [comment]
On the 26th, could we access the room from 1.30 - 1.45 and from 4.45 - 5pm?

**Comment by Kazykiddo** [comment]
Your request has been noted, and there will be people present at both timings to unlock the door. Thanks.

**Comment by 0nicholasloh** [comment]
Hi, sorry for the late notice, could we have access to the room from 5.30 pm - 5.45 pm on 29 October 2019 to retrieve items and on 30 October from 5 pm - 5.15 pm

**Comment by 0nicholasloh** [comment]
Hi, could we access the room on the 1st of November 2019 from 9.00 am to 9.15 am to retrieve items and on the 1st of November 2019 from 12.45 pm - 1.00 pm to return our items?

**Comment by 0nicholasloh** [comment]
Hi, could we have access to the room on 14 Nov 2019 from 5.45 pm - 6.00 pm and from 8.00 pm to 8.15 pm?

**Comment by Kazykiddo** [comment]
Hi, is this recurring? If so, perhaps you can open a new issue that lists all the dates, that is cleaning for us to refer to. I missed out on the above comment somehow. If you are alright with that, we will close this issue and you may start a new one.

Wrt to the access request, it has been noted and room will be unlocked during the requested timings.  Thanks.

**Comment by 0nicholasloh** [comment]
Thank you for your help, we will be closing this issue and starting a new issue
