### ISSUE TITLE
[ROOM]

### ISSUE THREAD

**Issue by RiriMoktar** [OpenSUTD/SAC-student-rules#12]
**Requester**
Sutdio

**What is the purpose?**
Housing Event

**Who is the Point of Contact?**
Megan(megan_moktar@mymail.sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
Tuesday, 11th June 2019, 6:30pm - 6:45pm, 9.45pm - 10pm
*Is this recurring? If yes, how often?**
No

**Comment by Kazykiddo** [comment]
Hi, I should be around to ensure the room is open during the requested timings.

**Comment by Kazykiddo** [comment]
close #12
