### ISSUE TITLE
[ROOM] Energy Club - Tinkerday Club Activities

### ISSUE THREAD

**Issue by baijialong** [OpenSUTD/SAC-student-rules#13]
**Requester**
Energy Club

**What is the purpose?**
e.g. Tinkerday (club activity)

**Who is the Point of Contact?**
e.g. Jialong (jialong_bai (at) mymail (dot) sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
Tuesday, 9th July 2019, 7.45pm and 10.15pm.
Tuesday, 16th July 2019, 7.45pm and 10.15pm
Tuesday, 23rd July 2019, 7.45pm and 10.15pm
Tuesday, 30th July 2019, 7.45pm and 10.15pm

**Is this recurring? If yes, how often?**
Yes, Weekly. Last session on 30 July 2019

**Comment by piroton** [comment]
With reference to the following conversation:

@baijialong , [09.07.19 08:40]
Would 10.15pm be too late to request access? I understand that people need to go back to rest too.
@piroton , [09.07.19 08:40]
Lemme check if there's anyone in who can help haha
@piroton , [09.07.19 08:44]
I think 745 Teck can help you, I'm checking right now about 10pm
@piroton , [09.07.19 08:45]
I'll update the issue when I get to work, but 2215 should also be doable
@baijialong , [09.07.19 08:45]
Okie. Thanks alot

Please find Teck if the door is not open at 1930, and Rathin will be locking up after.

Cheers,
GA

**Comment by piroton** [comment]
This issue will be closed once July is over - remember to re-open an issue if you need access again after July!

**Comment by baijialong** [comment]
Noted with thanks
