### ISSUE TITLE
[ROOM] SOAR Items

### ISSUE THREAD

**Issue by Fasermaler** [OpenSUTD/SAC-student-rules#15]
Requester
SOAR

What is the purpose?
Retrieve SOAR items

Who is the Point of Contact?
Amos Sim (amos_sim (at) mymail (dot) sutd.edu.sg)
Yan Le will be collecting the items

What date and what time are you requesting for it to be opened?
Friday 16 August 2019, 1300-1400

Is this recurring? If yes, how often?
No, just this one time

**Comment by Kazykiddo** [comment]
Request has been approved.

Point of Contact will be KY.
