### ISSUE TITLE
[ROOM] SOAR Inventory Check

### ISSUE THREAD

**Issue by Fasermaler** [OpenSUTD/SAC-student-rules#16]
Requester
SOAR

What is the purpose?
Stock Take SOAR items

Who is the Point of Contact?
Amos Sim (amos_sim (at) mymail (dot) sutd.edu.sg)
Yan Le and Wah Kit will run through the checklist

What date and what time are you requesting for it to be opened?
Wednesday 18 August 2019, 1600-1700

Is this recurring? If yes, how often?
No, just this one time

**Comment by Kazykiddo** [comment]
It's after the EPD welcome/back, I'll be around so there shouldn't be an issue.

**Comment by Fasermaler** [comment]
Thanks!
