### ISSUE TITLE
[ROOM] SOAR Inventory Check

### ISSUE THREAD

**Issue by Fasermaler** [OpenSUTD/SAC-student-rules#17]
Requester
SOAR

What is the purpose?
Stock Take and Label SOAR items

Who is the Point of Contact?
Amos Sim (amos_sim (at) mymail (dot) sutd.edu.sg)
Wah Kit will run through the checklist and do labeling of items

What date and what time are you requesting for it to be opened?
Friday 27 September 2019, 1300-1500

Is this recurring? If yes, how often?
No, just this one time

**Comment by Kazykiddo** [comment]
We will ensure that the room is open at the requested time.
