### ISSUE TITLE
[ROOM] Civil Defence Lionhearters

### ISSUE THREAD

**Issue by adamidrislim** [OpenSUTD/SAC-student-rules#19]
**Requester**
CDLH

**What is the purpose?**
Updating internal logs and storing equipment in the SAC

**Who is the Point of Contact?**
Adam Idris (adam_lim@mymail.sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
Thursday 3rd Oct 7pm

**Is this recurring? If yes, how often?**
No

**Comment by lyqht** [comment]
Yeap it will be open.
