### ISSUE TITLE
[ROOM] Retrieval of First Aid Kits for Carnival Night

### ISSUE THREAD

**Issue by placid-brain** [OpenSUTD/SAC-student-rules#26]
**Requester**
SUTD Civil Defence Lion Hearters 

**What is the purpose?**
To retrieve first aid kits

**Who is the Point of Contact?**
Shwetha, shwetha_selvam@mymail.sutd.edu.sg

**What date and what time are you requesting for it to be opened?**
 Thursday, 7th November 2019, 1800-1830, and 2130-2200

**Is this recurring? If yes, how often?**
No

**Comment by Kazykiddo** [comment]
Noted. We will ensure that the room is open, however, can the request be from 2000 to 2200 hrs?

**Comment by placid-brain** [comment]
We will be collecting the equipment from 1800-1815 and we will return them back at about 2200 within the same time period. So it's like 2 time slots.

**Comment by Kazykiddo** [comment]
Noted. In that case your request should be from 1800-1830, and 2130-2200. We will ensure that the rooms are open during those 2 timeslots.

**Comment by placid-brain** [comment]
Ok noted, thank you!

**Comment by lyqht** [comment]
edited the request timeslots in the issue to match

**Comment by piroton** [comment]
Given that this is over, I'll be closing this issue. Remember to re-open (or open a new one) when you need it again!
