### ISSUE TITLE
[ROOM] Access to SAC 13.11.19

### ISSUE THREAD

**Issue by adamidrislim** [OpenSUTD/SAC-student-rules#28]
**Requester**
SUTD CDLH

**What is the purpose?**
Withdraw First Aid Kit

**Who is the Point of Contact?**
Adam Idris (adam_lim@mymail.sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
Wednesday 13.11.19 1445-1510 and 1800-1830

**Is this recurring? If yes, how often?**
No

**Comment by Kazykiddo** [comment]
Noted, there will be people around to unlock and lock up once you're done. Please be reminded that your access card is still required for the access to the Student Activity Center.
