### ISSUE TITLE
SAC STORE[ROOM]

### ISSUE THREAD

**Issue by rapidestlime** [OpenSUTD/SAC-student-rules#31]
**Requester**
Energy Club

**What is the purpose?**
Storing items in the room

**Who is the Point of Contact?**
nicholas_tan2@mymail.sutd.edu.sg 

**What date and what time are you requesting for it to be opened?**
 FRI  15TH NOV 2019, 11 TO 12PM

**Is this recurring? If yes, how often?**
NO

**Comment by piroton** [comment]
Done! Please remember to file one before coming next time.
