### ISSUE TITLE
SAC STORE [ROOM]

### ISSUE THREAD

**Issue by rapidestlime** [OpenSUTD/SAC-student-rules#33]
**Requester**
Energy Club

**What is the purpose?**
Loaning of item(power cable drum)

**Who is the Point of Contact?**
Nicholas, nicholas_tan2@mymail.sutd.edu.sg 

**What date and what time are you requesting for it to be opened?**
Monday, 9th december , 2.15pmto 2.45pm 

**Is this recurring? If yes, how often?**
No

**Comment by piroton** [comment]
It's done.
