### ISSUE TITLE
[ROOM] Grub Inventory Check

### ISSUE THREAD

**Issue by wei-si** [OpenSUTD/SAC-student-rules#34]
**Requester**
Grub Cub

**What is the purpose?**
Taking stock of Grub Club's equipment

**Who is the Point of Contact?**
Wei Si (weisi_soh (at) mymail (dot) sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
Thursday, 26th Dec 2019, 1pm to 3pm

**Is this recurring? If yes, how often?**
No

**Comment by wei-si** [comment]
It seems like today's not possible. Is tomorrow, 27th Dec, 11am-1pm or Monday, 30th Dec, 11am-1pm possible?

**Comment by tlkh** [comment]
The room has just been opened. Let me know if you are going to be here. @wei-si 

Else I’ll close the room.

**Comment by wei-si** [comment]
I'll be there, thanks :) @tlkh
