### ISSUE TITLE
Request to put 3D printer

### ISSUE THREAD

**Issue by lootr5858** [OpenSUTD/SAC-student-rules#36]
Request to put MegaS 3D printer in SAC till 27th Jan

**Comment by whenderpsfly** [comment]
Hi, can we have more details such as:
- Who you are
- Who does the printer belong to
- Point of Contact

**Comment by lootr5858** [comment]
Loo Tan Rong
The printer belongs to me
I will be in SAC the following week

**Comment by whenderpsfly** [comment]
Request is denied as the school's policy is that no personal items are allowed in the SAC. The SAC is a public space to allow all users to use the space for activities.
