### ISSUE TITLE
[SAC ROOM]

### ISSUE THREAD

**Issue by hihithisisme** [OpenSUTD/SAC-student-rules#38]
**Requester**
Energy Club

**What is the purpose?**
Stock Taking and Checking Specs

**Who is the Point of Contact?**
lexuan_soong@mymail.sutd.edu.sg

**What date and what time are you requesting for it to be opened?**
Wed 15th jan 2020 | 1645 to 1800 HRS

**Is this recurring? If yes, how often?**
No

**Comment by whenderpsfly** [comment]
Issue noted, will liaise with Point of Contact.
