### ISSUE TITLE
SPACE

### ISSUE THREAD

**Issue by Anirudh181001** [OpenSUTD/SAC-student-rules#42]
Hi!
IEEE would like to request for more space in the SAC as we have a few bulky items to store, and are out of space in our lockers. We would be grateful to be granted some storage space in the SAC to store the bulky air hockey table and the wooden 'IEEE' letters along with some scrap metal and projectors that we still find to be useful for our upcoming projects.
Thanks!
For any queries, pls feel free to contact Anirudh (Pres) at 98983402.
:)

**Comment by whenderpsfly** [comment]
Will arrange a timing to meet up and discuss

**Comment by whenderpsfly** [comment]
Locked storage room request approved. Items to be stored:
Air hockey table
"IEEE" Wooden letters with LED strips

Duration: Till 31/12/2020 (TBD)
