### ISSUE TITLE
[ROOM]

### ISSUE THREAD

**Issue by hihithisisme** [OpenSUTD/SAC-student-rules#45]
**Requester**
Energy Club

**What is the purpose?**
Prototyping for Club Workshop

**Who is the Point of Contact?**
Soong Le Xuan (lexuan_soong@mymail.sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
Monday, 3rd Feb, 2020, 1830 - 2200

**Is this recurring? If yes, how often?**
No

**Comment by whenderpsfly** [comment]
Noted, door will be open at the assigned time.
