### ISSUE TITLE
[ROOM]

### ISSUE THREAD

**Issue by quantumxt** [OpenSUTD/SAC-student-rules#46]
Requester
SOAR
What is the purpose?
Shifting of items
Who is the Point of Contact?
1004232@mymail.sutd.edu.sg

What date and what time are you requesting for it to be opened?
9pm 6th Feb 2020

Is this recurring? If yes, how often?
nope

**Comment by Kazykiddo** [comment]
Has the request been cancelled?

**Comment by quantumxt** [comment]
Yes
