### ISSUE TITLE
[ROOM]

### ISSUE THREAD

**Issue by senputra** [OpenSUTD/SAC-student-rules#47]
**Requester**
SOAR

**What is the purpose?**
Move items temporarily to Gunpla's room

**Who is the Point of Contact?**
Dody (dodysenz@gmail.com)

**What date and what time are you requesting for it to be opened?**
Thursday, Feb to 830pm to 930pm

**Is this recurring? If yes, how often?**
no

**Comment by senputra** [comment]
Correction: 
For the date and time

Thursday, 6 Feb 2020. 830pm to 930pm

**Comment by whenderpsfly** [comment]
Approved as this request is necessary for the installation of shelves. However, do take note to request earlier next time :)
