### ISSUE TITLE
SAC[ROOM]

### ISSUE THREAD

**Issue by senputra** [OpenSUTD/SAC-student-rules#49]
**Requester**
SOAR

**What is the purpose?**
Moving boxes back to the original storage room. 

**Who is the Point of Contact?**
Dody (dody_senputra@mymail.sutd.edu.sg )

**What date and what time are you requesting for it to be opened?**
Friday, 21st of Feb 2020, 4pm to 5pm

**Is this recurring? If yes, how often?**
No

**Comment by Kazykiddo** [comment]
Noted, person in charge of key will be present to open the door at the stipulated time.
