### ISSUE TITLE
[ROOM] IEEE had moved out the air hockey table and a few other stored items from the storage room in order to make room for installing the cabinets in the SAC. We would like to move back everything on this Monday, and therefore would like to have access to the storage room then.

### ISSUE THREAD

**Issue by Anirudh181001** [OpenSUTD/SAC-student-rules#50]
**Requester**
e.g. Gunpla Club, Energy Club, etc

**What is the purpose?**
e.g. Regular club activities

**Who is the Point of Contact?**
e.g. Gui An (guian_lee (at) mymail (dot) sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
e.g. Thursday, 6th June 2019, 7pm to 11pm

**Is this recurring? If yes, how often?**
e.g. Yes, Weekly

**Comment by whenderpsfly** [comment]
Closed.
