### ISSUE TITLE
Storage Space in SAC for 30.007 Project

### ISSUE THREAD

**Issue by jayycynn** [OpenSUTD/SAC-student-rules#51]
Dear Student Activities Center,

I am J-Cyn from EPD and my 30.007 team (Group 17) and we wrote in to you regarding borrowing of available storage space in the Student Activities Centre.  Our request was unofficially approved and we were told to open an issue here on your GitHub for administrative purposes.

Here is the information regarding the space we are borrowing:
1) What kinds of items you are intending to store - One fridge with a bit more additional space for other add-on components.
2) Rough size of item you are storing - Would need a 3m by 3m square space. Height of estimate about 180cm.
3) The dates you need to store things for (NO PERPETUITY) - 1st March 2020 to 1st May 2020.
4) Who is in charge, and how they are to be contacted - Matthew Leng, project manager of Group 17 in 30.007 course, contact number: [-snip-]
You may email all of us (email addresses in CC of this email).
5) Receive approval in writing from the rep you wrote to. - Please help us with this.
6) Move your items in on your indicated date, and place them down neatly. - We may move it in later, since we may not get approval by 1st March and would also need more time to get it ready and planned.

Yours Sincerely,
30.007 Group 17

**Comment by piroton** [comment]
Dear J-Cyn,

I would not recommend publicly exposing a phone number on the internet - I've edited your request for you.

Cheers.

**Comment by jayycynn** [comment]
Hi Gui An,

Thanks!
________________________________

**Comment by whenderpsfly** [comment]
Issue settled. Space has been assigned.
