### ISSUE TITLE
[ROOM] Retrieval of Items

### ISSUE THREAD

**Issue by wei-si** [OpenSUTD/SAC-student-rules#52]
**Requester**
Grub Club

**What is the purpose?**
Retrieving of Equipment

**Who is the Point of Contact?**
e.g. Wei Si (weisi_soh (at) mymail (dot) sutd.edu.sg)

**What date and what time are you requesting for it to be opened?**
e.g. Friday, 6 March 2020, 1pm

**Is this recurring? If yes, how often?**
e.g. No

**Comment by 0nicholasloh** [comment]
Hi, I've replied to you on telegram on how to access the room. Please close this issue if there are no more issues.
