### ISSUE TITLE
individual-users.md does not exist

### ISSUE THREAD

**Issue by tlkh** [OpenSUTD/SAC-student-rules#6]
`individual-users.md` file referenced from README does not exist

What is the policy for individual users who want to use the space? I want to take a small corner to semi-officially use for development for ISTD Living Lab (until the Lab space is handed over to ISTD and furnished).

**Comment by piroton** [comment]
I'll get into drafting up rules for individual users too. Cheers for reminding me - it slipped my mind.

**Comment by lyqht** [comment]
Issue was already resolved in https://github.com/OpenSUTD/SAC-student-rules/commit/79b02dc763940fa1e4e34d1cd503feb2777275b2
