### ISSUE TITLE
Purchase date requirement for inventory template

### ISSUE THREAD

**Issue by methylDragon** [OpenSUTD/SAC-student-rules#8]
I'd like to inquire about the purchase date field in the inventory template. Is it a requirement for every inventoried item to have a purchase date, and if so, why?

**Comment by piroton** [comment]
As far as possible, purchase dates should be put in for accounting purposes - also because it is useful to know the general age of a specific item so that appropriate measures / disposal can be arranged if it becomes too old to be servicable.
